version: '3'

services:
  app:
    build: ./docker/app
    volumes:
    - ./app:/var/www/
    ports: 
    - 8015:8000
    command:  >
      php
      artisan serv
      --port 8000
      --host 0.0.0.0
