version: "3"

services:
  app:
    build: ./docker/app
    volumes:
      - ./app:/var/www/
    ports:
      - "2000:8000"
    environment: 
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: lvbbs
      DB_USERNAME: laravel
      DB_PASSWORD: lvlaravel
    command: >
      php
      artisan serv
      --port 8000
      --host 0.0.0.0
  mysql:
    image: mysql
    ports:
      - "2010:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: jfiasdfe
      MYSQL_DATABASE: lvbbs
      MYSQL_USER: laravel
      MYSQL_PASSWORD: lvlaravel
