name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install build staff
      run: |
        sudo apt-get update
        sudo apt-get install nodejs 
